package cn.et.test.entity;

public class Emp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.id
     *
     * @mbg.generated Sat Dec 16 10:10:40 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.eName
     *
     * @mbg.generated Sat Dec 16 10:10:40 CST 2017
     */
    private String ename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.sex
     *
     * @mbg.generated Sat Dec 16 10:10:40 CST 2017
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.age
     *
     * @mbg.generated Sat Dec 16 10:10:40 CST 2017
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.phone
     *
     * @mbg.generated Sat Dec 16 10:10:40 CST 2017
     */
    private Integer phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.deptId
     *
     * @mbg.generated Sat Dec 16 10:10:40 CST 2017
     */
    private Integer deptid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.id
     *
     * @return the value of emp.id
     *
     * @mbg.generated Sat Dec 16 10:10:40 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.id
     *
     * @param id the value for emp.id
     *
     * @mbg.generated Sat Dec 16 10:10:40 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.eName
     *
     * @return the value of emp.eName
     *
     * @mbg.generated Sat Dec 16 10:10:40 CST 2017
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.eName
     *
     * @param ename the value for emp.eName
     *
     * @mbg.generated Sat Dec 16 10:10:40 CST 2017
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.sex
     *
     * @return the value of emp.sex
     *
     * @mbg.generated Sat Dec 16 10:10:40 CST 2017
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.sex
     *
     * @param sex the value for emp.sex
     *
     * @mbg.generated Sat Dec 16 10:10:40 CST 2017
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.age
     *
     * @return the value of emp.age
     *
     * @mbg.generated Sat Dec 16 10:10:40 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.age
     *
     * @param age the value for emp.age
     *
     * @mbg.generated Sat Dec 16 10:10:40 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.phone
     *
     * @return the value of emp.phone
     *
     * @mbg.generated Sat Dec 16 10:10:40 CST 2017
     */
    public Integer getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.phone
     *
     * @param phone the value for emp.phone
     *
     * @mbg.generated Sat Dec 16 10:10:40 CST 2017
     */
    public void setPhone(Integer phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.deptId
     *
     * @return the value of emp.deptId
     *
     * @mbg.generated Sat Dec 16 10:10:40 CST 2017
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.deptId
     *
     * @param deptid the value for emp.deptId
     *
     * @mbg.generated Sat Dec 16 10:10:40 CST 2017
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }
}